version: '3.8'
services:
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/psychological-support.war:/usr/local/tomcat/webapps/psychological-support.war
    restart: on-failure
